apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: pvc-cassandra
spec:
   volumeMode: Filesystem
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 10M
   storageClassName: slow
