apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10M
  storageClassName: slow
    