apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
spec:
  capacity:
    storage: 10M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /var/lib/data/mongo/
