apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: cassandra
spec:
   selector:
      matchLabels:
         app: cassandra
   serviceName: cassandra-service
   replicas: 1
   updateStrategy:
      type: RollingUpdate
   template:
      metadata:
         labels:
            app: cassandra
      spec:
         containers:
            - name: cassandra
              image: cassandra:latest
              imagePullPolicy: Always
              ports:
                 - containerPort: 7000
                   name: intra-node
                 - containerPort: 9042
                   name: cql
              volumeMounts: 
                 - name: cassandra-data
                   mountPath: "/db"
         volumes:  
              - name: cassandra-data
                persistentVolumeClaim: 
                   claimName: pvc-cassandra       
                 