apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: mongo
spec:
   selector:
      matchLabels:
         app: mongo
   serviceName: mongo-service
   updateStrategy:
      type: RollingUpdate
   template:
      metadata:
         labels:
            app: mongo
      spec:
        containers:
           - name: mongo
             image: mongo:latest
             imagePullPolicy: IfNotPresent
             ports:
                - containerPort: 27017
                  name: default
             volumeMounts:
                - name: mongo-data
                  mountPath: "/data"
        volumes:
           - name: mongo-data
             persistentVolumeClaim:
                claimName: pvc-mongo
                
