apiVersion: v1
kind: Service
metadata: 
   name: cassandra-service
spec:
   selector: 
      app: cassandra
   ports:
      - port: 7000
        targetPort: 7000
        name: intra-node
        
      - port: 9042
        targetPort: 9042
        name: cql
   clusterIP: None
        