apiVersion: v1
kind: Service
metadata:
   name: neo4j-service
   labels:
      app: neo4j-service
spec:
   ports:
      - port: 7474
        targetPort: 7474
        name: browser
        
      - port: 7687
        targetPort: 7687
        name: bolt
   selector:
      app: neo4j