apiVersion: v1
kind: Service
metadata: 
   name: newsfeed-app
spec:
   selector: 
      app: newsfeed-app
   ports: 
      - protocol: TCP
        port: 8080
        targetPort: 8080
   type: ClusterIP
