apiVersion: v1
kind: Service
metadata: 
   name: auth-app
   namespace: default
spec:
   selector: 
      app: auth-app
   ports: 
      - protocol: TCP
        port: 8080
        targetPort: 8080
   type: ClusterIP
