apiVersion: v1
kind: ConfigMap
metadata: 
   name: okta-service-config
data: 
   OKTA_ISSUER: https://dev-63954939.okta.com/oauth2/default
   CLIENT_ID: 0oa7451v81v4EeUIE5d7
   CLIENT_SECRET: p5OyBKFMohHIzfjKPdPUb5lk9fdsr_iuwH7IxHUq
   OKTA_TOKEN_URI: https://dev-63954939.okta.com/oauth2/default/v1/token
   CC_CLIENT_ID: 0oa7451v81v4EeUIE5d7
   CC_CLIENT_SECRET: p5OyBKFMohHIzfjKPdPUb5lk9fdsr_iuwH7IxHUq
   CC_SCOPE: custom
   